% -------------------------------------------------------------------
%  Generated by MATLAB on 3-Apr-2019 19:30:18
%  MATLAB version: 8.5.0.197613 (R2015a)
% -------------------------------------------------------------------
saveVarsMat = load('matlab.mat');

H1 = saveVarsMat.H1; % <1022x8176 double> too many elements

clear saveVarsMat;
